{% set name = "giashard" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/paracrawl/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 62b92258277656f8eced9e43910201c3d50c90eb7e2366f6929ff3ede1221e1f

build:
  skip: True  # [not linux64]
  number: 0
  binary_relocation: False

requirements:
  build:
    - go-cgo 1.18.3 hc2a3312_0

test:
  commands:
    - command -V giashard
    - command -V giashardid
    - giashard -h
    - giashard_id=$(giashardid www.example.com); [[ "$giashard_id" != "61" ]] && exit 1

about:
  home: https://github.com/paracrawl/giashard
  summary: Sharding program for Paracrawl
  license: MIT
  license_file: LICENSE.txt # https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually

extra:
  recipe-maintainers:
    - cgr71ii
