{% set name = "giashard" %}
{% set commit = "3f291bb38ad54333b5bb065df4ba26ad76a612dc" %}
{% set version = commit[:7] %}
{% set sha1value = commit %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/paracrawl/giashard
  git_rev: {{ commit }}
  sha1: {{ sha1value }}

build:
  skip: True  # [not linux64]
  number: 0
  binary_relocation: False

requirements:
  build:
    - go-cgo 1.18.3 hc2a3312_0

test:
  commands:
    - command -V giashard
    - command -V giashardid
    - giashard -h
    - giashard_id=$(giashardid www.example.com); [[ "$giashard_id" != "61" ]] && exit 1

about:
  home: https://github.com/paracrawl/giashard
  summary: Sharding program for Paracrawl
  license: MIT

extra:
  recipe-maintainers:
    - cgr71ii
