{% set package_name = "loomchild-segment-py" %}
{% set name = "loomchild-segment" %}
{% set version = "2.0.4.2" %}

package:
  name: {{ package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/loomchild-segment-{{ version }}.tar.gz
  sha256: 1072e46d5b67213a0ba7b7dc34696314d519a8cca324351339bb8932f326ac5a

build:
  skip: True  # [not linux64]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - maven
    - ant
  host:
    - pip
    - python
    - openjdk 8
  run:
    - python
    - toolwrapper >=0.4.1
    - openjdk 8

test:
  imports:
    - loomchild.segmenter
  commands:
    - pip check
    - python -c "from loomchild.segmenter import LoomchildSegmenter; segmenter = LoomchildSegmenter('en'); segments = segmenter.get_segmentation('Test line. Another line'); assert len(segments) == 2, f'Unexpected no. segments ({len(segments)})'"
  requires:
    - pip
    - python

about:
  home: https://github.com/bitextor/loomchild-segment-py
  summary: Python module to interface with Java Loomchild sentence segmenter
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - LICENSE-java-segment.txt

extra:
  recipe-maintainers:
    - cgr71ii
