{% set name = "uchardet" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/freedesktop/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 561db71ffe3b090da48cd17f441bb7976694db55edd9cc16a6bd6ffcb9e66e8f

build:
  skip: True  # [not linux64]
  script:
   - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release
   - make
   - make install
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - uchardet -h

about:
  home: https://github.com/freedesktop/uchardet
  summary: uchardet is an encoding detector library
  description: |
    uchardet is an encoding detector library, which takes a sequence
    of bytes in an unknown character encoding and attempts to determine
    the encoding of the text. Returned encoding names are iconv-compatible.
  license: MPL-1.1
  license_family: MOZILLA
  license_file: COPYING
  doc_url: https://www.freedesktop.org/wiki/Software/uchardet

extra:
  recipe-maintainers:
    - cgr71ii
